spring:
  application:
    name: bigs-externalApi
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://49.247.8.143:3306/acorncalendar
    username: acorncalendar
    password: acorn1calendar123!
    hikari:
      maximum-pool-size: 5
      idle-timeout: 30000
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true

data:
  url: http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst
  encodingKey: 0zU%2FWZhf15g3BqY3R4Uf2HRJJF5l%2FgTSU%2BkkPexxPmve6NxkzVR9fYjeFfHnmmHTUWjhNkOPEGsHD8yZzm3ynw%3D%3D
  decodingKey: 0zU/WZhf15g3BqY3R4Uf2HRJJF5l/gTSU+kkPexxPmve6NxkzVR9fYjeFfHnmmHTUWjhNkOPEGsHD8yZzm3ynw==

bigs:
  x: 61
  y: 131